-- ── Migration 006 : Payroll ───────────────────────────────────────────────────
-- Run this entire script in Supabase Dashboard → SQL Editor → New query

DROP TABLE IF EXISTS payroll CASCADE;

CREATE TABLE payroll (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  payroll_number   TEXT        NOT NULL UNIQUE,

  -- Employee snapshot (denormalised so history survives employee edits)
  employee_id      UUID        REFERENCES employees(id) ON DELETE SET NULL,
  employee_ref     TEXT        NOT NULL,     -- e.g. TVSSNEMP001
  employee_name    TEXT        NOT NULL,
  department       TEXT,
  designation      TEXT,

  -- Pay period
  pay_month        INTEGER     NOT NULL,
  pay_year         INTEGER     NOT NULL,

  -- Earnings (all monthly, INR)
  basic_salary         NUMERIC(12,2) NOT NULL DEFAULT 0,
  hra                  NUMERIC(12,2) NOT NULL DEFAULT 0,
  transport_allowance  NUMERIC(12,2) NOT NULL DEFAULT 0,
  medical_allowance    NUMERIC(12,2) NOT NULL DEFAULT 0,
  other_allowances     NUMERIC(12,2) NOT NULL DEFAULT 0,

  -- Deductions
  pf_deduction         NUMERIC(12,2) NOT NULL DEFAULT 0,
  esi_deduction        NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_deduction        NUMERIC(12,2) NOT NULL DEFAULT 0,
  other_deductions     NUMERIC(12,2) NOT NULL DEFAULT 0,

  -- Computed totals — generated by the database, never inserted manually
  total_earnings   NUMERIC(12,2) GENERATED ALWAYS AS (
                     basic_salary + hra + transport_allowance
                     + medical_allowance + other_allowances
                   ) STORED,

  total_deductions NUMERIC(12,2) GENERATED ALWAYS AS (
                     pf_deduction + esi_deduction + tax_deduction + other_deductions
                   ) STORED,

  net_salary       NUMERIC(12,2) GENERATED ALWAYS AS (
                     basic_salary + hra + transport_allowance
                     + medical_allowance + other_allowances
                     - pf_deduction - esi_deduction - tax_deduction - other_deductions
                   ) STORED,

  -- Payment info
  payment_status   TEXT        NOT NULL DEFAULT 'pending',
  payment_date     DATE,
  payment_mode     TEXT        NOT NULL DEFAULT 'bank_transfer',

  -- Attendance
  working_days     INTEGER     NOT NULL DEFAULT 26,
  days_worked      INTEGER     NOT NULL DEFAULT 26,

  remarks          TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- ── Constraints ────────────────────────────────────────────────────────────
  CONSTRAINT chk_payroll_pay_month      CHECK (pay_month BETWEEN 1 AND 12),
  CONSTRAINT chk_payroll_pay_year       CHECK (pay_year  >= 2020),
  CONSTRAINT chk_payroll_basic          CHECK (basic_salary        >= 0),
  CONSTRAINT chk_payroll_hra            CHECK (hra                 >= 0),
  CONSTRAINT chk_payroll_transport      CHECK (transport_allowance >= 0),
  CONSTRAINT chk_payroll_medical        CHECK (medical_allowance   >= 0),
  CONSTRAINT chk_payroll_other_allow    CHECK (other_allowances    >= 0),
  CONSTRAINT chk_payroll_pf             CHECK (pf_deduction        >= 0),
  CONSTRAINT chk_payroll_esi            CHECK (esi_deduction       >= 0),
  CONSTRAINT chk_payroll_tax            CHECK (tax_deduction       >= 0),
  CONSTRAINT chk_payroll_other_ded      CHECK (other_deductions    >= 0),
  CONSTRAINT chk_payroll_working_days   CHECK (working_days        > 0),
  CONSTRAINT chk_payroll_days_worked    CHECK (days_worked >= 0 AND days_worked <= working_days),
  CONSTRAINT chk_payroll_status         CHECK (payment_status IN ('pending','paid','on_hold','cancelled')),
  CONSTRAINT chk_payroll_mode           CHECK (payment_mode   IN ('bank_transfer','cash','cheque','upi')),

  -- One payroll record per employee per calendar month
  CONSTRAINT uq_payroll_employee_period UNIQUE (employee_ref, pay_month, pay_year)
);

-- ── Indexes ───────────────────────────────────────────────────────────────────
CREATE INDEX idx_payroll_employee_ref ON payroll (employee_ref);
CREATE INDEX idx_payroll_employee_id  ON payroll (employee_id) WHERE employee_id IS NOT NULL;
CREATE INDEX idx_payroll_status       ON payroll (payment_status);
CREATE INDEX idx_payroll_period       ON payroll (pay_year DESC, pay_month DESC);
CREATE INDEX idx_payroll_created_at   ON payroll (created_at DESC);

-- ── Row Level Security ────────────────────────────────────────────────────────
ALTER TABLE payroll ENABLE ROW LEVEL SECURITY;

CREATE POLICY payroll_all_authenticated
  ON payroll
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Notify PostgREST to reload its schema cache
NOTIFY pgrst, 'reload schema';
